// <auto-generated />
namespace PassWeb.Inf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTokenClass_NamespaceCorrection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTokenClass_NamespaceCorrection));
        
        string IMigrationMetadata.Id
        {
            get { return "201808100715102_AddTokenClass_NamespaceCorrection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
